### PR TITLE
Create end point for greeting

### PR DESCRIPTION
**Pull request by shahzaman900**
### Implementation

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize the project with Git.
- set up a project with the Postgres database.
- Create a table for storing messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from the table

### CODE REVIEW

**Comment by tugsem** [comment]
## Invalid Code Review Request ❌ 

Hi @shahzaman900 , 

While you made a great effort in this project, I cannot proceed to review your code.
doesn't have the correct Gitflow. Also, as per the requirements, please add a readme file using the microverse template for both of your front and backends with the corresponding link to the other repositories as stated below: </h2>
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by aamirkhan2478 — COMMENTED** [review]
Hi @shahzaman900, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that does not use correct git-flow please make sure your client-side link is working for now it's not working so kindly fix these issues :slightly_smiling_face: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by iambenkis** [comment]
> Hi @shahzaman900,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request 🔴 🔴 🔴
> You have submitted a project, that does not use correct git-flow please make sure your client-side link is working for now it's not working so kindly fix these issues 🙂
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Review by frank1738 — COMMENTED** [review]
Hi @shahzaman900 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Heads-up! 🌟 In this milestone, we're rolling with gitflow. 🚀 Remember, each feature branch needs to be compared to the dev/development branch. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
